/**
 * Deterministic, contract-shaped API fixtures for the redesigned Custom Code
 * Connect browser journeys. Every fixture mirrors the response shapes consumed
 * by app.js and the pipeline contracts in src/pipelineContracts.js and
 * src/artifactBundle.js.
 *
 * These are pure data objects. Use `applyDefaultRoutes(page)` to wire them into
 * Playwright request interception, or mix and match individual fixtures with
 * `routeFulfill(page, urlPattern, fixture)`.
 */

const BUILDSHIP_BASE_URL = "https://4tgke4.buildship.run";
const PIPELINE_ENDPOINT = `${BUILDSHIP_BASE_URL}/service/runpipeline`;
const IDENTITY_ENDPOINT = `${BUILDSHIP_BASE_URL}/authUserCheck`;

export const ENDPOINTS = {
  buildship: BUILDSHIP_BASE_URL,
  pipeline: PIPELINE_ENDPOINT,
  identity: IDENTITY_ENDPOINT,
  authSendMagicLink: `${BUILDSHIP_BASE_URL}/auth/send-magic-link`,
  authVerifyMagicLink: `${BUILDSHIP_BASE_URL}/auth/verify-magic-link`,
  authRefreshSession: `${BUILDSHIP_BASE_URL}/auth/refresh-session`,
  getSubscription: `${BUILDSHIP_BASE_URL}/stripe/get-subscription`,
  createCheckout: `${BUILDSHIP_BASE_URL}/stripe/create-checkout-session-intl`,
  createPortal: `${BUILDSHIP_BASE_URL}/stripe/create-portal-session`,
  connectFeedback: `${BUILDSHIP_BASE_URL}/connectFeedback`,
  deployCustomClasses:
    "https://ccc-ffai-runner-y5cyj3473a-uw.a.run.app/deployCustomClasses",
  flutterFlowListProjects: "https://api.flutterflow.io/v2/listProjects",
  flutterFlowLegacyListProjects:
    "https://api.flutterflow.io/v2/l/listProjects",
  flutterFlowExportCode: "https://api.flutterflow.io/v2/exportCode",
  flutterFlowSyncCustomCodeChanges:
    "https://api.flutterflow.io/v2/syncCustomCodeChanges",
  exchangeRates: "https://open.er-api.com/v6/latest/AUD",
};

function ok(body) {
  return { status: 200, body: JSON.stringify(body), contentType: "application/json" };
}

function err(status, body) {
  return { status, body: typeof body === "string" ? body : JSON.stringify(body), contentType: "application/json" };
}

export const guestIdentity = () =>
  ok({
    status: "guest",
    user_id: "guest-test-0001",
    identity_token: null,
    usage_count: 0,
    usage_month: new Date().toISOString().slice(0, 7),
  });

export const freeSubscription = () =>
  ok({
    data: {
      subscription: { status: "active", tier: "free" },
      priceId: null,
      usage_count: 0,
      usage_month: new Date().toISOString().slice(0, 7),
    },
  });

export const professionalSubscription = () =>
  ok({
    data: {
      subscription: {
        status: "active",
        tier: "professional_plan",
        priceId: "price_1T2ldCKszA2slvDXatdeCpbI",
      },
      priceId: "price_1T2ldCKszA2slvDXatdeCpbI",
      usage_count: 12,
      usage_month: new Date().toISOString().slice(0, 7),
    },
  });

export const powerSubscription = () =>
  ok({
    data: {
      subscription: {
        status: "active",
        tier: "power_developer",
        priceId: "price_powerDev_123",
      },
      priceId: "price_powerDev_123",
      usage_count: 47,
      usage_month: new Date().toISOString().slice(0, 7),
    },
  });

export const unresolvedSubscription = () =>
  ok({ error: "Subscription service temporarily unavailable" });

export const signedInSession = () =>
  ok({
    email: "test@example.com",
    sessionToken: "test-session-token-0001",
  });

export const magicLinkSent = () =>
  ok({ success: true, message: "Magic link sent" });

export const checkoutSession = () =>
  ok({ url: "https://checkout.stripe.com/mock-session" });

export const portalSession = () =>
  ok({ url: "https://billing.stripe.com/mock-portal" });

function buildArtifactBundle(artifacts) {
  return {
    schemaVersion: "1.0.0",
    id: "bundle-test-0001",
    title: "Deterministic test bundle",
    description: "Generated by browser fixture",
    artifacts: artifacts.map((artifact, index) => ({
      id: artifact.id ?? `${artifact.artifactType?.toLowerCase() ?? "file"}-${index + 1}`,
      artifactType: artifact.artifactType ?? "CodeFile",
      artifactName: artifact.artifactName ?? `TestArtifact${index + 1}`,
      fileName: artifact.fileName ?? `${artifact.artifactName ?? `TestArtifact${index + 1}`}.dart`,
      deployPath: artifact.deployPath ?? "",
      description: artifact.description ?? "",
      code: artifact.code ?? "// Test code",
      dependencies: artifact.dependencies ?? [],
      imports: artifact.imports ?? [],
      publicApi: artifact.publicApi ?? [],
      relationships: artifact.relationships ?? [],
      deployStatus: artifact.deployStatus ?? "pending",
      review: artifact.review ?? null,
      metadata: artifact.metadata ?? {},
      codeType: artifact.codeType ?? "C",
    })),
    dependencies: [],
    relationships: [],
    deployOrder: artifacts.map((_, index) => `file-${index + 1}`),
    warnings: [],
    metadata: {},
  };
}

export const oneArtifact = () =>
  ok({
    output: JSON.stringify(
      buildArtifactBundle([
        {
          id: "custom-action-greet-user",
          artifactType: "CustomAction",
          artifactName: "GreetUser",
          code: "import 'package:flutter/material.dart';\nFuture<String> greetUser() async { return 'Hello'; }",
          codeType: "A",
        },
      ]),
    ),
    usage_status: "success",
    usage_count: 1,
    usage_month: new Date().toISOString().slice(0, 7),
  });

export const manyArtifacts = () =>
  ok({
    output: JSON.stringify(
      buildArtifactBundle([
        {
          id: "custom-class-event-model",
          artifactType: "CustomClass",
          artifactName: "AgentEvent",
          code: "class AgentEvent { final String type; AgentEvent(this.type); }",
          codeType: "C",
        },
        {
          id: "custom-action-parse-event",
          artifactType: "CustomAction",
          artifactName: "ParseAgentEvent",
          code:
            "import 'package:flutter/material.dart';\nimport 'agent_event.dart';\nAgentEvent parseEvent(String raw) { return AgentEvent(raw); }",
          codeType: "A",
        },
        {
          id: "custom-widget-agent-view",
          artifactType: "CustomWidget",
          artifactName: "AgentView",
          code:
            "import 'package:flutter/material.dart';\nimport 'agent_event.dart';\nclass AgentView extends StatelessWidget { @override Widget build(BuildContext context) { return Container(); } }",
          codeType: "W",
        },
      ]),
    ),
    usage_status: "success",
    usage_count: 3,
    usage_month: new Date().toISOString().slice(0, 7),
  });

export const missingReviewScore = () =>
  ok({
    output: JSON.stringify({
      status: "pass",
      summary: "Bundle compiles but review score is absent",
      manualActions: [],
      findings: [],
      artifacts: [
        {
          id: "custom-action-greet-user",
          review: { status: "pass", findings: [] },
        },
      ],
    }),
  });

export const rejectedGeneration = () =>
  err(400, {
    error: "Policy violation: prompt requests unsupported platform behavior",
    message: "Generation rejected by model armor",
  });

export const partialDeploy = () =>
  err(207, {
    success: false,
    deployed: ["custom-class-event-model"],
    failed: [
      {
        id: "custom-widget-agent-view",
        error: "Widget signature references unknown parameter type",
      },
    ],
  });

export const unknownDeploy = () =>
  err(500, { message: "Deploy service returned an unrecognized response" });

export const emptyProjectList = () => ok({ success: true, value: JSON.stringify({ entries: [] }) });

export const sampleProjectList = () =>
  ok({
    success: true,
    value: JSON.stringify({
      entries: [
        { id: "proj-abc-123", project: { name: "Test Project Alpha" } },
        { id: "proj-def-456", project: { name: "Test Project Beta" } },
      ],
    }),
  });

export const projectExport = () =>
  ok({
    success: true,
    value: JSON.stringify({
      project_zip: "UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAbWV0YS5Z", // minimal fake zip
    }),
  });

export const customCodeSync = () =>
  ok({
    success: true,
    value: JSON.stringify({ message: "Custom code synced" }),
  });

export const exchangeRates = () =>
  ok({
    result: "success",
    base_code: "AUD",
    rates: { USD: 0.65, EUR: 0.6, GBP: 0.52 },
  });

/**
 * Fulfill a Playwright route with a deterministic fixture response.
 */
export async function routeFulfill(page, urlPredicate, fixture) {
  await page.route(urlPredicate, async (route) => {
    const response = typeof fixture === "function" ? fixture() : fixture;
    await route.fulfill(response);
  });
}

/**
 * Apply a safe default route map that isolates the test from external services.
 * Use this as the baseline in every browser journey, then override specific
 * endpoints to exercise auth, subscription or generation states.
 */
export async function applyDefaultRoutes(page, overrides = {}) {
  const routes = {
    [ENDPOINTS.identity]: guestIdentity(),
    [ENDPOINTS.authSendMagicLink]: magicLinkSent(),
    [ENDPOINTS.authVerifyMagicLink]: signedInSession(),
    [ENDPOINTS.authRefreshSession]: signedInSession(),
    [ENDPOINTS.getSubscription]: freeSubscription(),
    [ENDPOINTS.createCheckout]: checkoutSession(),
    [ENDPOINTS.createPortal]: portalSession(),
    [ENDPOINTS.connectFeedback]: ok({ success: true }),
    [ENDPOINTS.deployCustomClasses]: ok({ success: true, deployed: [] }),
    [ENDPOINTS.flutterFlowListProjects]: sampleProjectList(),
    [ENDPOINTS.flutterFlowLegacyListProjects]: sampleProjectList(),
    [ENDPOINTS.flutterFlowExportCode]: projectExport(),
    [ENDPOINTS.flutterFlowSyncCustomCodeChanges]: customCodeSync(),
    [ENDPOINTS.exchangeRates]: exchangeRates(),
    [ENDPOINTS.pipeline]: oneArtifact(),
    ...overrides,
  };

  await page.route("**/*", async (route) => {
    const url = route.request().url();
    const fixture = routes[url];
    if (fixture) {
      await route.fulfill(typeof fixture === "function" ? fixture() : fixture);
      return;
    }
    await route.continue();
  });
}
